apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: rollout-canary 
  newTag: v3.0
kind: Kustomization
namespace: cn-online
replicas:
- count: 1
  name: rollout-canary 
resources:
- ../../base
